name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  analyze:
    name: Security Analysis
    runs-on: windows-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: 'powershell'

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  test:
    name: Test PowerShell Script
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          Install-Module -Name PSScriptAnalyzer -Force
          Invoke-ScriptAnalyzer -Path ./ -Recurse -Settings PSGallery

